# Generated by Django 5.0.7 on 2024-08-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('is_open', models.BooleanField(default=False)),
                ('work_time_open', models.TimeField(blank=True, null=True)),
                ('work_time_close', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
