# Generated by Django 5.0.7 on 2024-08-05 21:09

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOptionGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('selection_type', models.CharField(choices=[('one', 'Only One'), ('multiple', 'Multiple')])),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('additional_option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.additionaloptiongroups')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=35)),
                ('description', models.TextField(max_length=300)),
                ('composition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name=35), size=None)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('additional_option', models.ManyToManyField(blank=True, to='menu.additionaloptions')),
                ('category', models.ManyToManyField(to='menu.categories')),
            ],
        ),
    ]
